import { ItemDef } from "../../../types/game";

export const DEFS: Record<string, ItemDef> = {
  // ======= 6大经典传奇特戒神殿 (专属特戒槽位，不占基础戒指位) =======
  'r_kuangfeng_ring': {
    id: 'r_kuangfeng_ring',
    name: '【特戒】狂风特戒',
    type: 'equipment',
    slot: 'special_wind',
    tier: 0,
    specialEffect: 'wind',
    baseQuality: 4,
    minDC: 30,
    maxDC: 60,
    minAC: 10,
    maxAC: 20,
    maxHp: 800,
    maxMp: 200,
    hasteBonus: 35, // 狂飙 +35 急速！
    critBonus: 12,
    lifestealBonus: 3,
    levelReq: 1,
    price: 150000,
    icon: '🌪️',
    desc: '【特戒神技·疾风】极限攻速狂飙 +35 急速，风雷残影连击触发率巨幅提升！'
  },
  'r_tanlan': {
    id: 'r_tanlan',
    name: '【特戒】贪婪特戒',
    type: 'equipment',
    slot: 'special_greed',
    tier: 0,
    specialEffect: 'greed',
    baseQuality: 4,
    minDC: 25,
    maxDC: 55,
    minAC: 10,
    maxAC: 20,
    maxHp: 800,
    maxMp: 200,
    critBonus: 10,
    levelReq: 1,
    price: 150000,
    icon: '💰',
    desc: '【特戒神技·聚宝】击杀怪物金币掉落 +150%，极品神装大爆几率翻倍提升！'
  },
  'r_mabi': {
    id: 'r_mabi',
    name: '【特戒】麻痹戒指',
    type: 'equipment',
    slot: 'special_paralyze',
    tier: 1,
    specialEffect: 'paralyze',
    baseQuality: 4,
    minDC: 80,
    maxDC: 160,
    minAC: 25,
    maxAC: 50,
    maxHp: 2500,
    maxMp: 600,
    critBonus: 15,
    hasteBonus: 15,
    lifestealBonus: 4,
    levelReq: 25,
    price: 350000,
    icon: '⚡',
    desc: '【特戒神技·石化】传奇终极控制特戒！攻击时 25% 几率使目标石化麻痹 3 秒，无法移动与反击！'
  },
  'r_hushen': {
    id: 'r_hushen',
    name: '【特戒】护身戒指',
    type: 'equipment',
    slot: 'special_protect',
    tier: 1,
    specialEffect: 'protect',
    baseQuality: 4,
    minDC: 60,
    maxDC: 130,
    minAC: 40,
    maxAC: 80,
    maxHp: 2000,
    maxMp: 4000,
    critBonus: 10,
    lifestealBonus: 3,
    levelReq: 25,
    price: 350000,
    icon: '🛡️',
    desc: '【特戒神技·护体】受到伤害的 80% 优先扣除法力值 (MP) 抵御伤害，化身不死金刚！'
  },
  'r_fuhuo': {
    id: 'r_fuhuo',
    name: '【特戒】复活戒指',
    type: 'equipment',
    slot: 'special_revive',
    tier: 2,
    specialEffect: 'revive',
    baseQuality: 4,
    minDC: 120,
    maxDC: 240,
    minAC: 35,
    maxAC: 70,
    maxHp: 5000,
    maxMp: 1200,
    critBonus: 12,
    hasteBonus: 12,
    lifestealBonus: 5,
    levelReq: 32,
    price: 500000,
    icon: '💖',
    desc: '【特戒神技·涅槃】受到致命伤害时免除阵亡，瞬间回满 100% 生命与魔法，并获3秒无敌金身 (CD 90秒)！'
  },
  'r_xingyun': {
    id: 'r_xingyun',
    name: '【特戒】幸运特戒',
    type: 'equipment',
    slot: 'special_luck',
    tier: 2,
    specialEffect: 'luck',
    baseQuality: 4,
    minDC: 140,
    maxDC: 280,
    minAC: 30,
    maxAC: 60,
    maxHp: 4000,
    maxMp: 1000,
    critBonus: 20,
    luck: 3,
    levelReq: 32,
    price: 550000,
    icon: '🎲',
    desc: '【特戒神技·天命】佩戴直接增加【幸运 Luck +3】，助力迅速达成运9极境·刀刀发挥最大攻击上限！'
  }
};
