import { ItemDef } from '../../types/game';

export const ITEM_DEFINITIONS: Record<string, ItemDef> = {
  // ======= 武器类 (Weapon) =======
  'w_wood_sword': {
    id: 'w_wood_sword',
    name: '木剑',
    type: 'equipment',
    slot: 'weapon',
    baseQuality: 0,
    minDC: 2,
    maxDC: 5,
    minAC: 0,
    maxAC: 0,
    maxHp: 10,
    maxMp: 0,
    levelReq: 1,
    price: 50,
    icon: '🗡️',
    desc: '初入江湖的新手佩剑，轻巧但杀伤力有限。'
  },
  'w_bronze_sword': {
    id: 'w_bronze_sword',
    name: '青铜剑',
    type: 'equipment',
    slot: 'weapon',
    baseQuality: 0,
    minDC: 3,
    maxDC: 7,
    minAC: 0,
    maxAC: 0,
    maxHp: 20,
    maxMp: 0,
    levelReq: 5,
    price: 150,
    icon: '🗡️',
    desc: '青铜打造的短剑，比木剑更为锋利耐用。'
  },
  'w_bahuang': {
    id: 'w_bahuang',
    name: '八荒',
    type: 'equipment',
    slot: 'weapon',
    baseQuality: 1,
    minDC: 4,
    maxDC: 12,
    minAC: 0,
    maxAC: 0,
    maxHp: 35,
    maxMp: 0,
    hasteBonus: 3,
    levelReq: 10,
    price: 450,
    icon: '⚔️',
    desc: '战修启蒙阔剑，势大力沉。'
  },
  'w_lingfeng': {
    id: 'w_lingfeng',
    name: '凌风',
    type: 'equipment',
    slot: 'weapon',
    baseQuality: 1,
    minDC: 6,
    maxDC: 14,
    minAC: 0,
    maxAC: 0,
    maxHp: 50,
    maxMp: 0,
    critBonus: 2,
    hasteBonus: 5,
    levelReq: 15,
    price: 1200,
    icon: '⚔️',
    desc: '剑如疾风，挥动间带有破空之声。'
  },
  'w_zhanma': {
    id: 'w_zhanma',
    name: '斩马刀',
    type: 'equipment',
    slot: 'weapon',
    baseQuality: 2,
    minDC: 8,
    maxDC: 20,
    minAC: 0,
    maxAC: 0,
    maxHp: 80,
    maxMp: 0,
    critBonus: 3,
    levelReq: 20,
    price: 3500,
    icon: '🔪',
    desc: '沉重的阔刃斩刀，可轻易破开猛兽硬甲。'
  },
  'w_lianyu': {
    id: 'w_lianyu',
    name: '炼狱',
    type: 'equipment',
    slot: 'weapon',
    baseQuality: 2,
    minDC: 12,
    maxDC: 28,
    minAC: 0,
    maxAC: 0,
    maxHp: 120,
    maxMp: 0,
    critBonus: 5,
    lifestealBonus: 1, // 炼狱吸血 1%
    levelReq: 26,
    price: 8500,
    icon: '🪓',
    desc: '双刃重斧，刃口泛着炼狱血光。'
  },
  'w_jingzhongyue': {
    id: 'w_jingzhongyue',
    name: '井中月',
    type: 'equipment',
    slot: 'weapon',
    baseQuality: 3,
    minDC: 16,
    maxDC: 32,
    minAC: 0,
    maxAC: 0,
    maxHp: 200,
    maxMp: 0,
    critBonus: 6,
    hasteBonus: 8,
    lifestealBonus: 2, // 井中月吸血 2%
    levelReq: 30,
    price: 25000,
    icon: '🌙',
    desc: '名唤井中月，圆刃如镜，出刀平稳极速。'
  },
  'w_caijue': {
    id: 'w_caijue',
    name: '裁决之杖',
    type: 'equipment',
    slot: 'weapon',
    baseQuality: 3,
    minDC: 15,
    maxDC: 45,
    minAC: 0,
    maxAC: 0,
    maxHp: 350,
    maxMp: 0,
    critBonus: 10,
    lifestealBonus: 3, // 裁决之杖吸血 3%
    levelReq: 35,
    price: 60000,
    icon: '🏏',
    desc: '黑铁精钢铸就的沉重巨杖，战士信仰神器！'
  },
  'w_tulong': {
    id: 'w_tulong',
    name: '烈焰屠龙',
    type: 'equipment',
    slot: 'weapon',
    baseQuality: 4,
    minDC: 30,
    maxDC: 75,
    minAC: 5,
    maxAC: 10,
    maxHp: 800,
    maxMp: 200,
    critBonus: 15,
    hasteBonus: 15,
    lifestealBonus: 5, // 烈焰屠龙吸血 5%
    levelReq: 40,
    price: 200000,
    icon: '🔥',
    desc: '武林至尊，宝刀屠龙！号令天下，莫敢不从！'
  },

  // ======= 盔甲衣服 (Armor) =======
  'a_buyi': {
    id: 'a_buyi',
    name: '粗布衣',
    type: 'equipment',
    slot: 'armor',
    baseQuality: 0,
    minDC: 0,
    maxDC: 0,
    minAC: 1,
    maxAC: 2,
    maxHp: 20,
    maxMp: 10,
    levelReq: 1,
    price: 40,
    icon: '🥋',
    desc: '最朴素的麻布衣裳。'
  },
  'a_qingkai': {
    id: 'a_qingkai',
    name: '轻型盔甲',
    type: 'equipment',
    slot: 'armor',
    baseQuality: 1,
    minDC: 0,
    maxDC: 1,
    minAC: 3,
    maxAC: 5,
    maxHp: 60,
    maxMp: 20,
    levelReq: 11,
    price: 500,
    icon: '🛡️',
    desc: '皮质混缀铁片的轻甲，防御力适中。'
  },
  'a_zhongkai': {
    id: 'a_zhongkai',
    name: '重盔甲',
    type: 'equipment',
    slot: 'armor',
    baseQuality: 2,
    minDC: 1,
    maxDC: 2,
    minAC: 5,
    maxAC: 10,
    maxHp: 150,
    maxMp: 40,
    levelReq: 22,
    price: 3000,
    icon: '🦺',
    desc: '精钢锻打的厚重战甲，能抵御强力物理冲击。'
  },
  'a_zhanshen': {
    id: 'a_zhanshen',
    name: '战神盔甲',
    type: 'equipment',
    slot: 'armor',
    baseQuality: 3,
    minDC: 2,
    maxDC: 4,
    minAC: 9,
    maxAC: 16,
    maxHp: 380,
    maxMp: 80,
    critBonus: 3,
    lifestealBonus: 1, // 战神盔甲吸血 1%
    levelReq: 33,
    price: 35000,
    icon: '🛡️',
    desc: '散发炽热战意的赤红重铠，战士高阶象征。'
  },
  'a_shengzhan': {
    id: 'a_shengzhan',
    name: '圣战宝甲',
    type: 'equipment',
    slot: 'armor',
    baseQuality: 4,
    minDC: 5,
    maxDC: 10,
    minAC: 14,
    maxAC: 25,
    maxHp: 900,
    maxMp: 150,
    critBonus: 5,
    hasteBonus: 5,
    lifestealBonus: 3, // 圣战宝甲吸血 3%
    levelReq: 40,
    price: 150000,
    icon: '👑',
    desc: '蕴含圣战英魂的神甲，攻防兼备，睥睨天下。'
  },

  // ======= 头盔 (Helmet) =======
  'h_qingtong': {
    id: 'h_qingtong',
    name: '青铜头盔',
    type: 'equipment',
    slot: 'helmet',
    baseQuality: 0,
    minDC: 0,
    maxDC: 0,
    minAC: 1,
    maxAC: 2,
    maxHp: 20,
    maxMp: 0,
    levelReq: 5,
    price: 100,
    icon: '🪖',
    desc: '简单的青铜护额头盔。'
  },
  'h_daoshi': {
    id: 'h_daoshi',
    name: '道士头盔',
    type: 'equipment',
    slot: 'helmet',
    baseQuality: 1,
    minDC: 0,
    maxDC: 1,
    minAC: 2,
    maxAC: 4,
    maxHp: 50,
    maxMp: 20,
    levelReq: 18,
    price: 1500,
    icon: '🎩',
    desc: '绘有清心符咒的软布硬盔。'
  },
  'h_heitie': {
    id: 'h_heitie',
    name: '黑铁头盔',
    type: 'equipment',
    slot: 'helmet',
    baseQuality: 3,
    minDC: 1,
    maxDC: 2,
    minAC: 5,
    maxAC: 9,
    maxHp: 180,
    maxMp: 30,
    critBonus: 2,
    lifestealBonus: 1, // 黑铁头盔吸血 1%
    levelReq: 30,
    price: 18000,
    icon: '🪖',
    desc: '极度沉重的玄铁头盔，坚硬无可匹敌。'
  },

  // ======= 项链 (Necklace) =======
  'n_chuantong': {
    id: 'n_chuantong',
    name: '传统项链',
    type: 'equipment',
    slot: 'necklace',
    baseQuality: 0,
    minDC: 0,
    maxDC: 1,
    minAC: 0,
    maxAC: 0,
    maxHp: 15,
    maxMp: 10,
    levelReq: 2,
    price: 80,
    icon: '📿',
    desc: '银链穿着绿石的简易饰物。'
  },
  'n_kuangfeng': {
    id: 'n_kuangfeng',
    name: '狂风项链',
    type: 'equipment',
    slot: 'necklace',
    baseQuality: 2,
    minDC: 1,
    maxDC: 3,
    minAC: 0,
    maxAC: 0,
    maxHp: 60,
    maxMp: 20,
    hasteBonus: 15, // 狂风增加大量攻速
    levelReq: 19,
    price: 5000,
    icon: '🌪️',
    desc: '引动疾风之力的奇特项链，大幅提升出手速度。'
  },
  'n_jiyi': {
    id: 'n_jiyi',
    name: '记忆项链',
    type: 'equipment',
    slot: 'necklace',
    baseQuality: 3,
    minDC: 2,
    maxDC: 6,
    minAC: 0,
    maxAC: 1,
    maxHp: 120,
    maxMp: 50,
    critBonus: 5,
    hasteBonus: 8,
    lifestealBonus: 2, // 记忆项链吸血 2%
    levelReq: 32,
    price: 32000,
    icon: '💎',
    desc: '记忆套装之一，散发着时空波动的神秘蓝芒。'
  },

  // ======= 手镯 (Bracelets) =======
  'b_tieshou': {
    id: 'b_tieshou',
    name: '铁手镯',
    type: 'equipment',
    slot: 'bracelet_l',
    baseQuality: 0,
    minDC: 0,
    maxDC: 1,
    minAC: 0,
    maxAC: 1,
    maxHp: 10,
    maxMp: 0,
    levelReq: 3,
    price: 60,
    icon: '⭕',
    desc: '铁片弯折制成的手镯。'
  },
  'b_jinshou': {
    id: 'b_jinshou',
    name: '金手镯',
    type: 'equipment',
    slot: 'bracelet_l',
    baseQuality: 1,
    minDC: 0,
    maxDC: 2,
    minAC: 1,
    maxAC: 2,
    maxHp: 40,
    maxMp: 10,
    hasteBonus: 4,
    levelReq: 16,
    price: 1200,
    icon: '✨',
    desc: '黄金打造的护腕手镯，攻守平衡。'
  },
  'b_qishi': {
    id: 'b_qishi',
    name: '骑士手镯',
    type: 'equipment',
    slot: 'bracelet_l',
    baseQuality: 3,
    minDC: 2,
    maxDC: 5,
    minAC: 1,
    maxAC: 3,
    maxHp: 100,
    maxMp: 0,
    critBonus: 3,
    hasteBonus: 6,
    lifestealBonus: 2, // 骑士手镯吸血 2%
    levelReq: 30,
    price: 26000,
    icon: '🛡️',
    desc: '名誉骑士佩戴的精钢手镯，锋芒毕露。'
  },

  // ======= 戒指 (Rings) =======
  'r_gutong': {
    id: 'r_gutong',
    name: '古铜戒指',
    type: 'equipment',
    slot: 'ring_l',
    baseQuality: 0,
    minDC: 0,
    maxDC: 2,
    minAC: 0,
    maxAC: 0,
    maxHp: 10,
    maxMp: 0,
    levelReq: 3,
    price: 70,
    icon: '💍',
    desc: '简单的青铜小戒指。'
  },
  'r_shanhu': {
    id: 'r_shanhu',
    name: '珊瑚戒指',
    type: 'equipment',
    slot: 'ring_l',
    baseQuality: 1,
    minDC: 1,
    maxDC: 5,
    minAC: 0,
    maxAC: 0,
    maxHp: 30,
    maxMp: 0,
    critBonus: 2,
    levelReq: 18,
    price: 2000,
    icon: '🪸',
    desc: '深海红珊瑚雕琢而成的战力戒指。'
  },
  'r_liliang': {
    id: 'r_liliang',
    name: '力量戒指',
    type: 'equipment',
    slot: 'ring_l',
    baseQuality: 3,
    minDC: 3,
    maxDC: 9,
    minAC: 0,
    maxAC: 0,
    maxHp: 90,
    maxMp: 0,
    critBonus: 6,
    lifestealBonus: 2, // 力量戒指吸血 2%
    levelReq: 32,
    price: 38000,
    icon: '💪',
    desc: '蕴含无匹蛮力的赤金指环，能极大提升暴击概率。'
  },
  'r_mabi': {
    id: 'r_mabi',
    name: '特戒·麻痹戒指',
    type: 'equipment',
    slot: 'ring_l',
    baseQuality: 4,
    minDC: 5,
    maxDC: 12,
    minAC: 2,
    maxAC: 4,
    maxHp: 250,
    maxMp: 100,
    critBonus: 10,
    hasteBonus: 12,
    lifestealBonus: 3, // 麻痹特戒吸血 3%
    levelReq: 40,
    price: 250000,
    icon: '⚡',
    desc: '传奇终极特戒！攻击时有概率麻痹目标使其无法动弹！'
  },

  // ======= 药水类 (Potions) =======
  'pot_hp_small': {
    id: 'pot_hp_small',
    name: '金创药(小)',
    type: 'potion',
    baseQuality: 0,
    minDC: 0,
    maxDC: 0,
    minAC: 0,
    maxAC: 0,
    maxHp: 0,
    maxMp: 0,
    recoverHp: 80,
    levelReq: 1,
    price: 20,
    icon: '🧪',
    desc: '恢复 80 点生命值。'
  },
  'pot_hp_large': {
    id: 'pot_hp_large',
    name: '强效金创药',
    type: 'potion',
    baseQuality: 1,
    minDC: 0,
    maxDC: 0,
    minAC: 0,
    maxAC: 0,
    maxHp: 0,
    maxMp: 0,
    recoverHp: 300,
    levelReq: 10,
    price: 100,
    icon: '🍷',
    desc: '强效药剂，恢复 300 点生命值。'
  },
  'pot_mp_large': {
    id: 'pot_mp_large',
    name: '强效魔法药',
    type: 'potion',
    baseQuality: 1,
    minDC: 0,
    maxDC: 0,
    minAC: 0,
    maxAC: 0,
    maxHp: 0,
    maxMp: 0,
    recoverMp: 200,
    levelReq: 10,
    price: 100,
    icon: '🍶',
    desc: '强效蓝药，恢复 200 点法力值。'
  },
  'pot_sun': {
    id: 'pot_sun',
    name: '万年雪霜',
    type: 'potion',
    baseQuality: 3,
    minDC: 0,
    maxDC: 0,
    minAC: 0,
    maxAC: 0,
    maxHp: 0,
    maxMp: 0,
    recoverHp: 800,
    recoverMp: 400,
    levelReq: 25,
    price: 500,
    icon: '❄️',
    desc: '天山雪霜，瞬回 800 生命与 400 魔法，保命良药！'
  }
};
